#!/usr/bin/env bash
Bash script that loops from 1 to 10 and displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, and displays Best School for the other iterations, using the while loop and the if, elif, and else statements.
